name: Build a Docker image and push it to ACR

on:
  push: 
    branches: [main]

  workflow_dispatch:

env:
  TAG: 1
  SERVER: demoscopy.azurecr.io
  IMAGE: demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.SERVER }}
          username: ${{ secrets.user_name }}
          password: ${{ secrets.user_password }}

      - run: |
          docker build . -t ${{ env.SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.SERVER }}/${{ env.IMAGE }}:${{ env.TAG }}
